import Head from "next/head";
import React from "react";
import Footer from "../Footer";
import { Container } from "@chakra-ui/react";
import Header from "../Header/index";
import './Layout.module.scss';

interface Props {
  children: any;
}

const Layout: React.FC<Props> = ({ children }) => {
  return (
    <>
      <Head>
        <title>Lucas Montegú - Javascript Developer</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="preconnect" href="https://fonts.gstatic.com" />
        <link
          href="https://fonts.googleapis.com/css2?family=Inter:wght@200;300;400;600;800;900&display=swap"
          rel="stylesheet"
        ></link>
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Container maxW="container.xl">
        <Header />
        <main>
          {children}
        </main>
        <Footer />
      </Container>
    </>
  );
};

export default Layout;
